name = "Mechanical Journeys"
author = "Lemonzy"
version = "1.2.4"
description = "Create sophisticated machines in an exciting, immersive Vanilla+ world full of adventurous challenges!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb5bc666b2438b3ffca95b77cfd539fbbdf3816bf30f75ba62513d1b8502eb2a"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
