name = "Mechanical Journeys"
author = "Lemonzy"
version = "1.2.1"
description = "Create sophisticated machines in an exciting, immersive Vanilla+ world full of adventurous challenges!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4891af4ffed0cfe4196ad7ce1226da332d3a3d534c019d6d812e75d522c4102"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
